IGV: igv::LaneDetector Class Reference
igv::LaneDetector Class Reference
Class that Detects Lanes From Images.
#include <LaneDetection.hpp>
Public Member Functions
void DetectLanes (cv::Mat &Image)
Detects Lanes and Fills the Private Data with the Lane Data.
uint32_t GetNumLanes () const
Return the Number of Lanes Detected.
bool isBusy () const
Return if the Lane Detector is Busy.
const std::array< Lane, 4 > & GetLanes () const
Return the Array full of detected Lanes.
Static Public Member Functions
static uint32_t DetectLanes (std::array< Lane, 4 > &LaneArray, cv::Mat &image)
Detects Lanes and Fills array with detected lanes.
Private Attributes
bool busy
If the Lane Detector is busy with an operation.
std::array< Lane, 4 > lanes
Array full of viable lanes.
uint32_t numlanes
Total Number of Lanes Detected.
Detailed Description
Class that Detects Lanes From Images.
This Class has both a static function as well as a member function to Detect Lanes from a standard opencv image type. They have similar algoritms and nearly the same runtime, if possible, use the member function as it is thread safe.
Member Function Documentation
DetectLanes() [1/2]
void igv::LaneDetector::DetectLanes (cv::Mat & Image)
Detects Lanes and Fills the Private Data with the Lane Data.
Parameters
Image Photo To Detect Lanes From
Returns
void
DetectLanes() [2/2]
static uint32_t igv::LaneDetector::DetectLanes (std::array< Lane, 4 > & LaneArray, cv::Mat & image) static
Detects Lanes and Fills array with detected lanes.
Parameters
LaneArray Array of Lanes to be filled
image Photo To Detect Lanes From
Returns
Number of Lanes Detected
Referenced by igv::Test::LaneDetectionTest().
GetLanes()
const std::array<Lane, 4>& igv::LaneDetector::GetLanes () const inline
Return the Array full of detected Lanes.
Returns
Array of Lanes used to hold lanes
References lanes.
Referenced by igv::Test::LaneDetectionTest().
GetNumLanes()
uint32_t igv::LaneDetector::GetNumLanes () const inline
Return the Number of Lanes Detected.
Returns
uint32_t: The number of Lanes Detected
References numlanes.
Referenced by igv::Test::LaneDetectionTest().
isBusy()
bool igv::LaneDetector::isBusy () const inline
Return if the Lane Detector is Busy.
Returns
bool: If the LaneDetector is Busy with an Operation
References busy.
Field Documentation
busy
bool igv::LaneDetector::busy private
If the Lane Detector is busy with an operation.
Referenced by isBusy().
lanes
std::array<Lane, 4> igv::LaneDetector::lanes private
Array full of viable lanes.
Referenced by GetLanes().
numlanes
uint32_t igv::LaneDetector::numlanes private
Total Number of Lanes Detected.
Referenced by GetNumLanes().
The documentation for this class was generated from the following file:
/home/orion/Code/Projects/IGV/include/LaneDetection.hpp