IGV: igv::Test Class Reference
igv::Test Class Reference
Test Class.
#include <test.hpp>
Public Member Functions
Test (const char *logfile)
Test ()=default
Constructs Test Object.
~Test ()
Destructs Test Object.
bool OpenLogFile (const char *logfile)
Opens a Logfile to write into.
bool Ready ()
Checks if the Test is ready to be run.
bool RunAllTests ()
bool CameraTest ()
Tests to see if the Cameras are connected and get valid images.
bool MotorTest ()
Tests all of the Motor Functionality.
bool LIDARTest ()
Tests LIDAR Functionality.
bool GPSTest ()
Tests all of the GPS Functionality.
bool LaneDetectionTest (string filename)
Tests all of the Lane Detection Functionality.
bool ObjectDetectionTest ()
Tests all of the Lane Detection Functionality.
bool SensorsTest ()
Tests all of the Sensors and Their Functionality.
Private Attributes
ofstream logfile
ostream object for the log file
Detailed Description
Test Class.
Constructor & Destructor Documentation
Test() [1/2]
Test::Test (const char * logfile)
Test() [2/2]
igv::Test::Test () default
Constructs Test Object.
Constructs Test Object without a log file.
Parameters
logfile File to print logs to
~Test()
igv::Test::~Test ()
Destructs Test Object.
References logfile.
Member Function Documentation
CameraTest()
bool Test::CameraTest ()
Tests to see if the Cameras are connected and get valid images.
Test:
Camera Test
Return values
bool If the Test is passed
References igv::Camera::Capture(), igv::Camera::GetImage(), LANECAMPORT, logfile, OBJCAMPORT, and Ready().
Referenced by main(), and RunAllTests().
GPSTest()
bool Test::GPSTest ()
Tests all of the GPS Functionality.
Test:
GPS Test
Return values
bool If the Test was Passed
Referenced by main(), and RunAllTests().
LaneDetectionTest()
bool Test::LaneDetectionTest (string filename)
Tests all of the Lane Detection Functionality.
Test:
Lane Detection Test
Parameters
filename Image file name to open
Return values
bool Returns if the Test was passed
References igv::LaneDetector::DetectLanes(), igv::LaneDetector::GetLanes(), igv::LaneDetector::GetNumLanes(), logfile, numlanes, and Ready().
Referenced by main(), and RunAllTests().
LIDARTest()
bool Test::LIDARTest ()
Tests LIDAR Functionality.
Test:
LIDAR Test
Return values
bool If the Test was passed
Referenced by main(), and RunAllTests().
MotorTest()
bool Test::MotorTest ()
Tests all of the Motor Functionality.
Test:
Motor Test
Return values
bool If the Test was passed
Referenced by main(), and RunAllTests().
ObjectDetectionTest()
bool Test::ObjectDetectionTest ()
Tests all of the Lane Detection Functionality.
Test:
Object Detection Test
Return values
bool If the Test was passed
Referenced by main(), and RunAllTests().
OpenLogFile()
igv::Test::OpenLogFile (const char * logfile)
Opens a Logfile to write into.
Parameters
logfile Name of logfile to open
Returns
bool: If the Log File was opened
Ready()
igv::Test::Ready ()
Checks if the Test is ready to be run.
Returns
bool: If the Test Class if Ready
References logfile.
Referenced by CameraTest(), and LaneDetectionTest().
RunAllTests()
bool Test::RunAllTests ()
References CameraTest(), GPSTest(), LaneDetectionTest(), LIDARTest(), MotorTest(), ObjectDetectionTest(), and SensorsTest().
Referenced by main().
SensorsTest()
bool Test::SensorsTest ()
Tests all of the Sensors and Their Functionality.
Test:
Sensors Test
Return values
bool If the Test was passed
Referenced by RunAllTests().
Field Documentation
logfile
ofstream igv::Test::logfile private
ostream object for the log file
Referenced by CameraTest(), LaneDetectionTest(), Ready(), and ~Test().
The documentation for this class was generated from the following files:
/home/orion/Code/Projects/IGV/test/test.hpp
/home/orion/Code/Projects/IGV/test/test.cpp