IGV: igv::IGV Class Reference
igv::IGV Class Reference
The Complete Vehicle Class.
#include <IGV.hpp>
Public Member Functions
IGV ()
Constructs an IGV object.
void Setup ()
Starts all Sensors and Probes them all.
void Run ()
Starts running autonomously.
Private Attributes
MotorController MC
ObjDetector OD
LaneDetector LD
Camera LCam
Camera OCam
LIDAR lidar
GPS gps
UltraSonic us
Friends
void ObjDetection (IGV *igv)
Detects Objects.
void LaneDetection (IGV *igv)
Detects Lanes using the Land Detector in the IGV.
void LidarLoop (IGV *igv)
Probes the LIDAR.
void GPSLoop (IGV *igv)
Probes the GPS.
void SensorLoop (IGV *igv)
Probes all of the misc sensors
Detailed Description
The Complete Vehicle Class.
Constructor & Destructor Documentation
IGV()
IGV::IGV ()
Constructs an IGV object.
Member Function Documentation
Run()
void IGV::Run ()
Starts running autonomously.
Setup()
void IGV::Setup ()
Starts all Sensors and Probes them all.
References GPSLoop, LaneDetection, LidarLoop, ObjDetection, and SensorLoop.
Friends And Related Function Documentation
GPSLoop
void GPSLoop (IGV * igv) friend
Probes the GPS.
Parameters
igv Pointer to vehicle to use
Referenced by Setup().
LaneDetection
void LaneDetection (IGV * igv) friend
Detects Lanes using the Land Detector in the IGV.
Parameters
igv Pointer to IGV to use
Referenced by Setup().
LidarLoop
void LidarLoop (IGV * igv) friend
Probes the LIDAR.
Parameters
igv Pointer to IGV to use
Referenced by Setup().
ObjDetection
void ObjDetection (IGV * igv) friend
Detects Objects.
Parameters
igv Pointer to an IGV instance
Referenced by Setup().
SensorLoop
void SensorLoop (IGV * igv) friend
Probes all of the misc sensors
Parameters
igv Pointer to vehicle to use
Referenced by Setup().
Field Documentation
gps
GPS igv::IGV::gps private
LCam
Camera igv::IGV::LCam private
LD
LaneDetector igv::IGV::LD private
lidar
LIDAR igv::IGV::lidar private
MC
MotorController igv::IGV::MC private
OCam
Camera igv::IGV::OCam private
OD
ObjDetector igv::IGV::OD private
us
UltraSonic igv::IGV::us private
The documentation for this class was generated from the following files:
/home/orion/Code/Projects/IGV/include/IGV.hpp
/home/orion/Code/Projects/IGV/src/IGV.cpp